# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AzureSqlEnv: "Server=tcp:asynchandler.database.windows.net,1433;Initial Catalog=asynchandler;Persist Security Info=False;User ID=ah;Password=#asynchandler@2024;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=10;"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: 8.0.x
    # - name: Restore dependencies
    #   run: dotnet restore
    # - name: Build
    #   run: dotnet build --no-restore

    - name: set env
      run: export AzureSqlEnv="Server=tcp:asynchandler.database.windows.net,1433;Initial Catalog=asynchandler;Persist Security Info=False;User ID=ah;Password=#asynchandler@2024;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=10;"
      shell: bash

    - name: show envs
      run: export
      shell: bash

    - name: Test
      run: dotnet test --no-build --verbosity normal
